const countries = [
  { name: "Afghanistan", iso3: "AFG", phoneCode: "+93", iso: "AF" },
  { name: "Albania", iso3: "ALB", phoneCode: "+355", iso: "AL" },
  { name: "Algeria", iso3: "DZA", phoneCode: "+213", iso: "DZ" },
  { name: "Andorra", iso3: "AND", phoneCode: "+376", iso: "AD" },
  { name: "Angola", iso3: "AGO", phoneCode: "+244", iso: "AO" },
  { name: "Argentina", iso3: "ARG", phoneCode: "+54", iso: "AR" },
  { name: "Armenia", iso3: "ARM", phoneCode: "+374", iso: "AM" },
  { name: "Australia", iso3: "AUS", phoneCode: "+61", iso: "AU" },
  { name: "Austria", iso3: "AUT", phoneCode: "+43", iso: "AT" },
  { name: "Azerbaijan", iso3: "AZE", phoneCode: "+994", iso: "AZ" },
  { name: "Bahamas", iso3: "BHS", phoneCode: "+1-242", iso: "BS" },
  { name: "Bahrain", iso3: "BHR", phoneCode: "+973", iso: "BH" },
  { name: "Bangladesh", iso3: "BGD", phoneCode: "+880", iso: "BD" },
  { name: "Barbados", iso3: "BRB", phoneCode: "+1-246", iso: "BB" },
  { name: "Belarus", iso3: "BLR", phoneCode: "+375", iso: "BY" },
  { name: "Belgium", iso3: "BEL", phoneCode: "+32", iso: "BE" },
  { name: "Belize", iso3: "BLZ", phoneCode: "+501", iso: "BZ" },
  { name: "Benin", iso3: "BEN", phoneCode: "+229", iso: "BJ" },
  { name: "Bhutan", iso3: "BTN", phoneCode: "+975", iso: "BT" },
  { name: "Bolivia", iso3: "BOL", phoneCode: "+591", iso: "BO" },
  {
    name: "Bosnia and Herzegovina",
    iso3: "BIH",
    phoneCode: "+387",
    iso: "BA",
  },
  { name: "Botswana", iso3: "BWA", phoneCode: "+267", iso: "BW" },
  { name: "Brazil", iso3: "BRA", phoneCode: "+55", iso: "BR" },
  { name: "Brunei", iso3: "BRN", phoneCode: "+673", iso: "BN" },
  { name: "Bulgaria", iso3: "BGR", phoneCode: "+359", iso: "BG" },
  { name: "Burkina Faso", iso3: "BFA", phoneCode: "+226", iso: "BF" },
  { name: "Burundi", iso3: "BDI", phoneCode: "+257", iso: "BI" },
  { name: "Cabo Verde", iso3: "CPV", phoneCode: "+238", iso: "CV" },
  { name: "Cambodia", iso3: "KHM", phoneCode: "+855", iso: "KH" },
  { name: "Cameroon", iso3: "CMR", phoneCode: "+237", iso: "CM" },
  { name: "Canada", iso3: "CAN", phoneCode: "+1", iso: "CA" },
  {
    name: "Central African Republic",
    iso3: "CAF",
    phoneCode: "+236",
    iso: "CF",
  },
  { name: "Chad", iso3: "TCD", phoneCode: "+235", iso: "TD" },
  { name: "Chile", iso3: "CHL", phoneCode: "+56", iso: "CL" },
  { name: "China", iso3: "CHN", phoneCode: "+86", iso: "CN" },
  { name: "Colombia", iso3: "COL", phoneCode: "+57", iso: "CO" },
  { name: "Comoros", iso3: "COM", phoneCode: "+269", iso: "KM" },
  {
    name: "Congo, Democratic Republic of the",
    iso3: "COD",
    phoneCode: "+243",
    iso: "CD",
  },
  {
    name: "Congo, Republic of the",
    iso3: "COG",
    phoneCode: "+242",
    iso: "CG",
  },
  { name: "Costa Rica", iso3: "CRI", phoneCode: "+506", iso: "CR" },
  { name: "Croatia", iso3: "HRV", phoneCode: "+385", iso: "HR" },
  { name: "Cuba", iso3: "CUB", phoneCode: "+53", iso: "CU" },
  { name: "Cyprus", iso3: "CYP", phoneCode: "+357", iso: "CY" },
  { name: "Czech Republic", iso3: "CZE", phoneCode: "+420", iso: "CZ" },
  { name: "Denmark", iso3: "DNK", phoneCode: "+45", iso: "DK" },
  { name: "Djibouti", iso3: "DJI", phoneCode: "+253", iso: "DJ" },
  { name: "Dominica", iso3: "DMA", phoneCode: "+1-767", iso: "DM" },
  {
    name: "Dominican Republic",
    iso3: "DOM",
    phoneCode: "+1-809",
    iso: "DO",
  },
  { name: "Ecuador", iso3: "ECU", phoneCode: "+593", iso: "EC" },
  { name: "Egypt", iso3: "EGY", phoneCode: "+20", iso: "EG" },
  { name: "El Salvador", iso3: "SLV", phoneCode: "+503", iso: "SV" },
  {
    name: "Equatorial Guinea",
    iso3: "GNQ",
    phoneCode: "+240",
    iso: "GQ",
  },
  { name: "Eritrea", iso3: "ERI", phoneCode: "+291", iso: "ER" },
  { name: "Estonia", iso3: "EST", phoneCode: "+372", iso: "EE" },
  { name: "Eswatini", iso3: "SWZ", phoneCode: "+268", iso: "SZ" },
  { name: "Ethiopia", iso3: "ETH", phoneCode: "+251", iso: "ET" },
  { name: "Fiji", iso3: "FJI", phoneCode: "+679", iso: "FJ" },
  { name: "Finland", iso3: "FIN", phoneCode: "+358", iso: "FI" },
  { name: "France", iso3: "FRA", phoneCode: "+33", iso: "FR" },
  { name: "Gabon", iso3: "GAB", phoneCode: "+241", iso: "GA" },
  { name: "Gambia", iso3: "GMB", phoneCode: "+220", iso: "GM" },
  { name: "Georgia", iso3: "GEO", phoneCode: "+995", iso: "GE" },
  { name: "Germany", iso3: "DEU", phoneCode: "+49", iso: "DE" },
  { name: "Ghana", iso3: "GHA", phoneCode: "+233", iso: "GH" },
  { name: "Greece", iso3: "GRC", phoneCode: "+30", iso: "GR" },
  { name: "Grenada", iso3: "GRD", phoneCode: "+1-473", iso: "GD" },
  { name: "Guatemala", iso3: "GTM", phoneCode: "+502", iso: "GT" },
  { name: "Guinea", iso3: "GIN", phoneCode: "+224", iso: "GN" },
  { name: "Guinea-Bissau", iso3: "GNB", phoneCode: "+245", iso: "GW" },
  { name: "Guyana", iso3: "GUY", phoneCode: "+592", iso: "GY" },
  { name: "Haiti", iso3: "HTI", phoneCode: "+509", iso: "HT" },
  { name: "Honduras", iso3: "HND", phoneCode: "+504", iso: "HN" },
  { name: "Hungary", iso3: "HUN", phoneCode: "+36", iso: "HU" },
  { name: "Iceland", iso3: "ISL", phoneCode: "+354", iso: "IS" },
  { name: "India", iso3: "IND", phoneCode: "+91", iso: "IN" },
  { name: "Indonesia", iso3: "IDN", phoneCode: "+62", iso: "ID" },
  { name: "Iran", iso3: "IRN", phoneCode: "+98", iso: "IR" },
  { name: "Iraq", iso3: "IRQ", phoneCode: "+964", iso: "IQ" },
  { name: "Ireland", iso3: "IRL", phoneCode: "+353", iso: "IE" },
  { name: "Israel", iso3: "ISR", phoneCode: "+972", iso: "IL" },
  { name: "Italy", iso3: "ITA", phoneCode: "+39", iso: "IT" },
  { name: "Jamaica", iso3: "JAM", phoneCode: "+1-876", iso: "JM" },
  { name: "Japan", iso3: "JPN", phoneCode: "+81", iso: "JP" },
  { name: "Jordan", iso3: "JOR", phoneCode: "+962", iso: "JO" },
  { name: "Kazakhstan", iso3: "KAZ", phoneCode: "+7", iso: "KZ" },
  { name: "Kenya", iso3: "KEN", phoneCode: "+254", iso: "KE" },
  { name: "Kiribati", iso3: "KIR", phoneCode: "+686", iso: "KI" },
  { name: "Korea, North", iso3: "PRK", phoneCode: "+850", iso: "KP" },
  { name: "Korea, South", iso3: "KOR", phoneCode: "+82", iso: "KR" },
  { name: "Kuwait", iso3: "KWT", phoneCode: "+965", iso: "KW" },
  { name: "Kyrgyzstan", iso3: "KGZ", phoneCode: "+996", iso: "KG" },
  { name: "Laos", iso3: "LAO", phoneCode: "+856", iso: "LA" },
  { name: "Latvia", iso3: "LVA", phoneCode: "+371", iso: "LV" },
  { name: "Lebanon", iso3: "LBN", phoneCode: "+961", iso: "LB" },
  { name: "Lesotho", iso3: "LSO", phoneCode: "+266", iso: "LS" },
  { name: "Liberia", iso3: "LBR", phoneCode: "+231", iso: "LR" },
  { name: "Libya", iso3: "LBY", phoneCode: "+218", iso: "LY" },
  { name: "Liechtenstein", iso3: "LIE", phoneCode: "+423", iso: "LI" },
  { name: "Lithuania", iso3: "LTU", phoneCode: "+370", iso: "LT" },
  { name: "Luxembourg", iso3: "LUX", phoneCode: "+352", iso: "LU" },
  { name: "Madagascar", iso3: "MDG", phoneCode: "+261", iso: "MG" },
  { name: "Malawi", iso3: "MWI", phoneCode: "+265", iso: "MW" },
  { name: "Malaysia", iso3: "MYS", phoneCode: "+60", iso: "MY" },
  { name: "Maldives", iso3: "MDV", phoneCode: "+960", iso: "MV" },
  { name: "Mali", iso3: "MLI", phoneCode: "+223", iso: "ML" },
  { name: "Malta", iso3: "MLT", phoneCode: "+356", iso: "MT" },
  {
    name: "Marshall Islands",
    iso3: "MHL",
    phoneCode: "+692",
    iso: "MH",
  },
  { name: "Mauritania", iso3: "MRT", phoneCode: "+222", iso: "MR" },
  { name: "Mauritius", iso3: "MUS", phoneCode: "+230", iso: "MU" },
  { name: "Mexico", iso3: "MEX", phoneCode: "+52", iso: "MX" },
  { name: "Micronesia", iso3: "FSM", phoneCode: "+691", iso: "FM" },
  { name: "Moldova", iso3: "MDA", phoneCode: "+373", iso: "MD" },
  { name: "Monaco", iso3: "MCO", phoneCode: "+377", iso: "MC" },
  { name: "Mongolia", iso3: "MNG", phoneCode: "+976", iso: "MN" },
  { name: "Montenegro", iso3: "MNE", phoneCode: "+382", iso: "ME" },
  { name: "Morocco", iso3: "MAR", phoneCode: "+212", iso: "MA" },
  { name: "Mozambique", iso3: "MOZ", phoneCode: "+258", iso: "MZ" },
  { name: "Myanmar", iso3: "MMR", phoneCode: "+95", iso: "MM" },
  { name: "Namibia", iso3: "NAM", phoneCode: "+264", iso: "NA" },
  { name: "Nauru", iso3: "NRU", phoneCode: "+674", iso: "NR" },
  { name: "Nepal", iso3: "NPL", phoneCode: "+977", iso: "NP" },
  { name: "Netherlands", iso3: "NLD", phoneCode: "+31", iso: "NL" },
  { name: "New Zealand", iso3: "NZL", phoneCode: "+64", iso: "NZ" },
  { name: "Nicaragua", iso3: "NIC", phoneCode: "+505", iso: "NI" },
  { name: "Niger", iso3: "NER", phoneCode: "+227", iso: "NE" },
  { name: "Nigeria", iso3: "NGA", phoneCode: "+234", iso: "NG" },
  {
    name: "North Macedonia",
    iso3: "MKD",
    phoneCode: "+389",
    iso: "MK",
  },
  { name: "Norway", iso3: "NOR", phoneCode: "+47", iso: "NO" },
  { name: "Oman", iso3: "OMN", phoneCode: "+968", iso: "OM" },
  { name: "Pakistan", iso3: "PAK", phoneCode: "+92", iso: "PK" },
  { name: "Palau", iso3: "PLW", phoneCode: "+680", iso: "PW" },
  { name: "Panama", iso3: "PAN", phoneCode: "+507", iso: "PA" },
  {
    name: "Papua New Guinea",
    iso3: "PNG",
    phoneCode: "+675",
    iso: "PG",
  },
  { name: "Paraguay", iso3: "PRY", phoneCode: "+595", iso: "PY" },
  { name: "Peru", iso3: "PER", phoneCode: "+51", iso: "PE" },
  { name: "Philippines", iso3: "PHL", phoneCode: "+63", iso: "PH" },
  { name: "Poland", iso3: "POL", phoneCode: "+48", iso: "PL" },
  { name: "Portugal", iso3: "PRT", phoneCode: "+351", iso: "PT" },
  { name: "Qatar", iso3: "QAT", phoneCode: "+974", iso: "QA" },
  { name: "Romania", iso3: "ROU", phoneCode: "+40", iso: "RO" },
  { name: "Russia", iso3: "RUS", phoneCode: "+7", iso: "RU" },
  { name: "Rwanda", iso3: "RWA", phoneCode: "+250", iso: "RW" },
  {
    name: "Saint Kitts and Nevis",
    iso3: "KNA",
    phoneCode: "+1-869",
    iso: "KN",
  },
  { name: "Saint Lucia", iso3: "LCA", phoneCode: "+1-758", iso: "LC" },
  {
    name: "Saint Vincent and the Grenadines",
    iso3: "VCT",
    phoneCode: "+1-784",
    iso: "VC",
  },
  { name: "Samoa", iso3: "WSM", phoneCode: "+685", iso: "WS" },
  { name: "San Marino", iso3: "SMR", phoneCode: "+378", iso: "SM" },
  {
    name: "Sao Tome and Principe",
    iso3: "STP",
    phoneCode: "+239",
    iso: "ST",
  },
  { name: "Saudi Arabia", iso3: "SAU", phoneCode: "+966", iso: "SA" },
  { name: "Senegal", iso3: "SEN", phoneCode: "+221", iso: "SN" },
  { name: "Serbia", iso3: "SRB", phoneCode: "+381", iso: "RS" },
  { name: "Seychelles", iso3: "SYC", phoneCode: "+248", iso: "SC" },
  { name: "Sierra Leone", iso3: "SLE", phoneCode: "+232", iso: "SL" },
  { name: "Singapore", iso3: "SGP", phoneCode: "+65", iso: "SG" },
  { name: "Slovakia", iso3: "SVK", phoneCode: "+421", iso: "SK" },
  { name: "Slovenia", iso3: "SVN", phoneCode: "+386", iso: "SI" },
  {
    name: "Solomon Islands",
    iso3: "SLB",
    phoneCode: "+677",
    iso: "SB",
  },
  { name: "Somalia", iso3: "SOM", phoneCode: "+252", iso: "SO" },
  { name: "South Africa", iso3: "ZAF", phoneCode: "+27", iso: "ZA" },
  { name: "South Sudan", iso3: "SSD", phoneCode: "+211", iso: "SS" },
  { name: "Spain", iso3: "ESP", phoneCode: "+34", iso: "ES" },
  { name: "Sri Lanka", iso3: "LKA", phoneCode: "+94", iso: "LK" },
  { name: "Sudan", iso3: "SDN", phoneCode: "+249", iso: "SD" },
  { name: "Suriname", iso3: "SUR", phoneCode: "+597", iso: "SR" },
  { name: "Sweden", iso3: "SWE", phoneCode: "+46", iso: "SE" },
  { name: "Switzerland", iso3: "CHE", phoneCode: "+41", iso: "CH" },
  { name: "Syria", iso3: "SYR", phoneCode: "+963", iso: "SY" },
  { name: "Taiwan", iso3: "TWN", phoneCode: "+886", iso: "TW" },
  { name: "Tajikistan", iso3: "TJK", phoneCode: "+992", iso: "TJ" },
  { name: "Tanzania", iso3: "TZA", phoneCode: "+255", iso: "TZ" },
  { name: "Thailand", iso3: "THA", phoneCode: "+66", iso: "TH" },
  { name: "Timor-Leste", iso3: "TLS", phoneCode: "+670", iso: "TL" },
  { name: "Togo", iso3: "TGO", phoneCode: "+228", iso: "TG" },
  { name: "Tonga", iso3: "TON", phoneCode: "+676", iso: "TO" },
  {
    name: "Trinidad and Tobago",
    iso3: "TTO",
    phoneCode: "+1-868",
    iso: "TT",
  },
  { name: "Tunisia", iso3: "TUN", phoneCode: "+216", iso: "TN" },
  { name: "Turkey", iso3: "TUR", phoneCode: "+90", iso: "TR" },
  { name: "Turkmenistan", iso3: "TKM", phoneCode: "+993", iso: "TM" },
  { name: "Tuvalu", iso3: "TUV", phoneCode: "+688", iso: "TV" },
  { name: "Uganda", iso3: "UGA", phoneCode: "+256", iso: "UG" },
  { name: "Ukraine", iso3: "UKR", phoneCode: "+380", iso: "UA" },
  {
    name: "United Arab Emirates",
    iso3: "ARE",
    phoneCode: "+971",
    iso: "AE",
  },
  { name: "United Kingdom", iso3: "GBR", phoneCode: "+44", iso: "GB" },
  { name: "United States", iso3: "USA", phoneCode: "+1", iso: "US" },
  { name: "Uruguay", iso3: "URY", phoneCode: "+598", iso: "UY" },
  { name: "Uzbekistan", iso3: "UZB", phoneCode: "+998", iso: "UZ" },
  { name: "Vanuatu", iso3: "VUT", phoneCode: "+678", iso: "VU" },
  { name: "Vatican City", iso3: "VAT", phoneCode: "+379", iso: "VA" },
  { name: "Venezuela", iso3: "VEN", phoneCode: "+58", iso: "VE" },
  { name: "Vietnam", iso3: "VNM", phoneCode: "+84", iso: "VN" },
  { name: "Yemen", iso3: "YEM", phoneCode: "+967", iso: "YE" },
  { name: "Zambia", iso3: "ZMB", phoneCode: "+260", iso: "ZM" },
  { name: "Zimbabwe", iso3: "ZWE", phoneCode: "+263", iso: "ZW" },
];
const fs = require("fs");
const a = () => {
  const b = countries.map((x) => ({
    ...x,
    iso: x.iso.toLowerCase(),
    iso3: x.iso3.toLowerCase(),
  }));
  fs.writeFileSync(`state2.json`, JSON.stringify(b));
};

a();
