import Head from "next/head";
import { Inter } from "next/font/google";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import PageLayout from "@/components/page-layout/PageLayout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        home
        {/* <CountrySelect /> */}
        {/* <div style={{ display: "flex", flexWrap: "wrap" }}>
          {a.map((item) => (
            <div style={{ margin: "8px" }}>
              <img
                alt="imga"
                src={`https://flagsapi.com/${item.iso}/shiny/32.png`}
              />{" "}
            </div>
          ))}
        </div> */}
      </PageLayout>
    </>
  );
}

export async function getStaticProps({ locale }: { locale: string }) {
  return {
    props: {
      ...(await serverSideTranslations(locale)),
    },
    revalidate: 60,
  };
}
